AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "tndx\nThe Twitter ndx\n"
Globals:
  Function:
    Timeout: 60
Resources:
  tndxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-1cgv746ppjbj9/7cfe33677ba2ed7726b98994968a3dfb
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
      - arm64
      Role:
        Fn::GetAtt:
        - FunctionRole
        - Arn
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: TndxParameterStoreAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ssm:GetParameter*
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/tndx*
      - PolicyName: TndxS3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:ListBucket
            Resource: arn:aws:s3:::is-tndx
          - Effect: Allow
            Action:
            - s3:PutObject
            Resource: arn:aws:s3:::is-tndx/*
      - PolicyName: TndxSQSAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            Resource: arn:aws:sqs:us-east-1:150319663043:tndx-entities
          - Effect: Allow
            Action:
            - ssm:GetParameter
            Resource: arn:aws:ssm:us-east-1:150319663043:parameter/tndx*
      - PolicyName: TndxDDBAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            Resource: arn:aws:dynamodb:us-east-1:150319663043:table/tndx
